Assignment 5 submission
IEEE-NITK/SummerProjects17 pull request #100
Opened 2017-07-09 15:53 UTC by NachiketUN

2017-07-11 05:53 UTC, grakshith requested changes

2017-07-11 05:53 UTC, hehaichi commented on FP-Erlang/Week 6/Assignment 5/Nachiket/assign5.erl
> +
Add two argument versions of the above functions by making calls to the curried functions

2017-07-11 07:52 UTC, NachiketUN commented on FP-Erlang/Week 6/Assignment 5/Nachiket/assign5.erl
> +
Changes requested are implemented.
Four new functions of two arguments added.

2017-07-12 14:59 UTC, grakshith approved these changes

2017-07-12 14:59 UTC, merged