Assignment 2
IEEE-NITK/SummerProjects17 pull request #52
Opened 2017-05-29 18:21 UTC by rahulsnkr

2017-05-30 03:52 UTC, vilas897 requested changes
Great work on the assignment! Although, try making a few changes. 
Merge sort seems to be taking too much time. Just check your code again and try to optimize it. Ideally, merge sort should be the fastest among the 5. 
Also, write a non-tail recursive solution to Fibonacci, time it and include the comparison between both non-tail recursive as well as the tail recursive version of the algorithm in your readme file.

2017-05-30 15:45 UTC, hehaichi commented on FP-Erlang/Week 3/Assignment 2/Rahul/assignment2.erl
> +insort(Sorted,[H|T]) -> insort([X||X <- Sorted, X<H]++[H]++[X||X <- Sorted, X>=H],T).
Do you notice how similar insertion sort and quick sort are in functional programming?
Rather, all sorts are similar in functional languages. These names like quick sort, insertion sort are given to algorithms implemented in imperative languages like C, C++, Java

2017-05-30 15:56 UTC, grakshith requested changes

2017-05-30 15:56 UTC, hehaichi commented on FP-Erlang/Week 3/Assignment 2/Rahul/assignment2.erl
> +mergesort([],[H|T]) when T== [] -> H;
Can be written as `mergesort([], [H|[]])`

2017-05-30 15:56 UTC, hehaichi commented on FP-Erlang/Week 3/Assignment 2/Rahul/assignment2.erl
> +mergesort(Sorted,[H|T],NewList) when T==[] -> mergesort(H,[],[],T,NewList++[Sorted]);
Same as the above comment. Can be written as `mergesort(Sorted,[H|[]],NewList)`

2017-05-30 15:56 UTC, hehaichi commented on FP-Erlang/Week 3/Assignment 2/Rahul/assignment2.erl
> +fibonacci(N,Series,[H|[H1|_]]) -> fibonacci(N-1,Series++[H+H1],[H1,H+H1]).
Where's the non tail recursive one?

2017-05-30 18:15 UTC, rahulsnkr commented on FP-Erlang/Week 3/Assignment 2/Rahul/assignment2.erl
> +insort(Sorted,[H|T]) -> insort([X||X <- Sorted, X<H]++[H]++[X||X <- Sorted, X>=H],T).
Yeah I did notice it, I actually thought I wrote the same code twice quite a few times.

2017-05-31 02:03 UTC, hehaichi commented
Why did you close this?

2017-05-31 03:38 UTC, vilas897 approved these changes

2017-05-31 03:41 UTC, merged