Assignment 5
IEEE-NITK/SummerProjects17 pull request #98
Opened 2017-07-09 05:53 UTC by rahulsnkr

2017-07-11 05:48 UTC, grakshith requested changes

2017-07-11 05:48 UTC, hehaichi commented on FP-Erlang/Week 6/Rahul/assignment5.erl
> +lessThanX(X) -> fun(Y) -> X>Y end.
Include the two argument versions of the functions by making implicit calls to the curried functions.

2017-07-12 07:12 UTC, rahulsnkr commented
Made the necessary changes.

2017-07-12 14:57 UTC, grakshith approved these changes

2017-07-12 14:57 UTC, merged